-- Hand-written rewritten descriptions for the top on-sale startups, so our pages
-- aren't a 1:1 copy of trustmrr.com. Self-contained: creates the table if needed,
-- then seeds rows. ON CONFLICT DO NOTHING — never overwrites an existing rewrite.
-- Run once in the Supabase SQL Editor.

create table if not exists public.startup_descriptions (
  slug        text primary key,
  description text not null,
  original    text,
  model       text,
  updated_at  timestamptz not null default now()
);
alter table public.startup_descriptions enable row level security;

insert into public.startup_descriptions (slug, description, original, model) values
  ('1lookup', 'A real-time validation tool for phone, email, and IP data, delivered through a single API.', 'The #1 tool for validating phone, email and IP data in real time. All through one powerful API.', 'hand'),
  ('doors-delivered', 'DoorsDelivered.com is an online retailer of internal doors and related accessories. Its catalogue covers modern and classic styles — including white, black, pocket, concealed, aluminium, frameless, and fire doors — aimed at homeowners, developers, and trade professionals. The shop combines competitive prices, support, and nationwide delivery to make choosing internal doors straightforward.', 'DoorsDelivered.com is your trusted online supplier of high-quality internal doors and accessories. We specialise in a wide range of modern and classic solutions, including white doors, black doors, pocket doors, concealed doors, aluminium doors, frameless doors, fire doors, etc.. Designed for homeowners, developers, and trade professionals.With competitive pricing, expert support, and fast nationwide delivery. DoorsDelivered.com makes choosing the right internal doors simple and hassle-free.', 'hand'),
  ('bullgpt-io', 'AI-assisted analysis aimed at a professional level of detail.', 'Get pro-level analysis instantly with AI.', 'hand'),
  ('launch-club', 'A SaaS focused on Reddit marketing and on improving visibility in AI search. It teaches business owners how to promote their products and provides members with supporting tools and content creation.', 'Reddit marketing to improve AI search.  SaaS helping business owners learn how to promote their products. Also provide tools and content creation for members.', 'hand'),
  ('post-bridge', 'Publish content to several social media platforms at once from a single place.', 'Post your content to multiple social media platforms at the same time, all-in one place.', 'hand'),
  ('lunchbreak', 'Lunchbreak rewrites AI-generated text so it passes the major detectors, such as Turnitin and GPTZero, while preserving the author''s natural tone and voice. It is aimed at students and professionals.', 'Lunchbreak helps students and professionals make AI-generated content undetectable across all major detectors, including Turnitin and GPTZero, while keeping their natural tone and voice.', 'hand'),
  ('fiddl-art', 'Fiddl.art is a platform for generating AI images and video with models like Nano Banana Pro, Flux 2, and Sora. Its Magic Mirror feature offers guided results, and a points-based economy lets users buy points or earn them through missions, uploads, and community activity. When others unlock your creations you can earn more points over time. Public galleries provide reference and ideas. There is no subscription — usage is pay-as-you-go.', 'Fiddl.art is a creative platform for high quality AI images and videos using models like Nano Banana Pro, Flux 2 and Sora. Magic Mirror gives fast guided results. A circular points economy lets you buy or earn points through missions, uploads and community activity. Others can unlock your creations so you earn more over time. Public galleries offer inspiration and learning. No subscription needed. Pay only for what you use.', 'hand'),
  ('setsmart', 'SetSmart is an AI sales setter that qualifies leads and books calls through Instagram DMs and WhatsApp. It supports custom scripts, lead filtering, and direct calendar booking around the clock, with integrations for Calendly, GHL, Zapier, and Make, and a quick setup.', 'AI sales setter that automatically qualifies your leads and books calls via Instagram DMs and WhatsApp. Custom scripts, smart filtering, direct calendar booking, 24/7. Integrates with Calendly, GHL, Zapier, Make and more. Setup in minutes.', 'hand'),
  ('pushouse', 'Pushouse offers software and services that help e-commerce businesses automate customer communication, marketing, and sales — mainly over WhatsApp and other digital channels. Capabilities include WhatsApp automation, AI-driven chat flows, order notifications, support automation, marketing tools, and integrations with e-commerce systems.', 'Pushouse provides software and technology services that enable e-commerce businesses to automate customer communication, marketing, and sales processes through WhatsApp and other digital channels. The platform offers WhatsApp automation, AI-powered chat flows, order notifications, customer support automation, digital marketing tools, and integration services with e-commerce systems to improve customer experience and increase online sales.', 'hand'),
  ('conductor', 'An API for QuickBooks Desktop and Enterprise.', 'The best QuickBooks Desktop & Enterprise API on the planet.', 'hand'),
  ('low-content-ai', 'Uses AI tools to produce low-content books prepared for publishing on Amazon.', 'Creates low-content books using AI tools, ready for publishing on Amazon.', 'hand'),
  ('facekit', 'A consumer app in the looksmaxxing / face-analysis niche, positioned as scalable. The listing notes proprietary backend data, with further detail available on request.', 'Highly profitable & scalable consumer app in the looksmaxxing / face analysis niche. Most unique and accurate app in this space. Includes very valuable data in the backend - to be elaborated on.', 'hand'),
  ('advise-so', 'An active community of marketers.', 'Vibrant and active community of marketers', 'hand'),
  ('gronk', 'Gronk is an AI assistant for creativity, productivity, and everyday tasks. In a single app it handles chat, image generation, quick answers, and general workflow support.', 'Meet Gronk, your powerful AI companion for creativity, productivity, and everyday problem solving. Chat smarter, generate images, get instant answers, and boost your workflow with one intelligent app.', 'hand'),
  ('storyshort', 'StoryShorts generates short videos from text prompts using AI.', 'StoryShorts helps to create short videos with AI based on text prompts.', 'hand'),
  ('atlas', 'Atlas is a personalized learning platform for students. Its AI reviews your class materials to help with homework and test preparation.', 'Atlas is a personalized learning platform for students. Atlas''s AI studies your class materials to help you nail your homework and ace your tests.', 'hand'),
  ('knightvision', 'Note: a sizable share of recurring revenue runs through Whop, a separate billing platform, and isn''t reflected in the Stripe MRR or all-time totals shown here — so actual MRR is higher.

Knightvision is an AI ad-intelligence and video-generation platform. Users buy credits to analyze social media ads and create UGC-style video content, with subscriptions billed through both Stripe and Whop.', 'Important: A significant portion of recurring revenue is processed through Whop (separate billing platform) and is NOT reflected in the Stripe MRR or all-time totals shown above. Actual MRR is meaningfully higher. 

AI-powered ad intelligence and video generation platform. Users purchase credits to analyze social media advertisements and generate UGC-style video content using AI tools, with subscriptions billed via both Stripe and Whop.', 'hand'),
  ('of-prompt-o', 'Digital products and services offering educational AI resources, charged at checkout.', 'Digital products/services for educational AI resources. We charge during checkout.', 'hand'),
  ('marky', 'A social media management tool aimed at self-publishing authors.', 'A tool for self-publishing authors to manage their social media.', 'hand'),
  ('virlo', 'Tools to track, manage, and make use of short-form content data.', 'Track, manage, leverage short-form data.', 'hand'),
  ('buildmyagent-io', 'BuildMyAgent.io is a web platform for designing, testing, and deploying AI agents and chatbots, built around LLMs and prompt engineering, and aimed at teams and agencies.', 'BuildMyAgent.io is a web-based platform that helps teams and agencies design, test, and deploy AI-driven agents and chatbots using LLMs and prompt engineering.', 'hand'),
  ('stat-ai', 'Stat AI is a sports-analysis app that applies AI to surface data-driven insights.', 'Stat AI is a sports analysis app that uses AI to provide data-driven decisions and insights.', 'hand'),
  ('plutio-super-work-ai', 'A single app for running, growing, and automating a business.', 'One app to run, grow, and automate your business.', 'hand'),
  ('seo-stack', 'SEO Stack is an SEO and marketing SaaS that pairs data warehousing with AI. It reworks the ideas behind Google Search Console and Analytics to help marketers improve results across search engines and LLMs, and includes AI/LLM visibility tracking.', 'SEO stack is an SEO/marketing SaaS that offers data warehousing with AI. It is a rebuild of Google search console with Google analytics, it allows SEOs and marketers to get better results in search engines and LLMs, it also provides AI and LLM visibility tracking.', 'hand'),
  ('brainrot-mov', 'A generator for Peter Griffin-style reels. The listing cites 10M+ followers and 10B+ views generated to date.', 'peter griffin reels generator (10M+ followers generated 10B+ views generated)', 'hand'),
  ('lancer-app', 'Lancer.app is an AI tool that automates the Upwork job-application process for freelancers and agencies.', 'Lancer.app is an AI-powered tool that automates job application process on Upwork for freelancers and agencies.', 'hand'),
  ('glamour', 'Glamour is an AI personal color-analysis app. Users upload a selfie and receive a seasonal color palette for clothing, makeup, and accessories. It runs on a subscription with roughly 9% churn and no refunds; the listing reports growth from $222 to $15.8K MRR over ten months, driven by Meta campaigns in Turkey.', 'Glamour is an AI-powered personal color analysis app helping users discover their ideal color palette for clothing, makeup, and accessories. Users upload a selfie and get personalized seasonal color analysis via AI. Subscription model with strong retention (~9% churn) and zero refunds. Revenue grew from $222 to $15.8K MRR in 10 months through Meta campaigns in Turkey alone.', 'hand'),
  ('autocontent-api', 'AutoContent API offers an API for automated content generation across several formats.', 'AutoContent API provides an API for automated content generation across multiple formats.', 'hand'),
  ('vidgenie-ai', 'Vidgenie.ai produces AI-generated videos for businesses and creators to use on social media.', 'Vidgenie.ai creates AI-generated videos for businesses and creators for social media use.', 'hand'),
  ('kortex-notebooklm', 'Kortex extends Google NotebookLM into a connected knowledge base, making it easier to capture notes and find them again later.', 'Kortex transforms Google NotebookLM into a dynamic, interconnected knowledge base. Capture everything, find anything, and never lose an insight again.', 'hand'),
  ('nutria', 'nutrIA is an AI nutrition app centered on habit tracking, personalized feedback, and daily engagement, combining food recognition, recommendations, and gamified challenges to support retention. The listing notes around 65% margins, steady MRR, an established brand in Chile, and a growing user base, with potential expansion across LATAM and B2B partnerships with nutritionists and health institutions.', 'nutrIA is an AI-powered nutrition app focused on habit tracking, personalized feedback and daily engagement. The app combines food recognition, smart recommendations and gamified challenges to drive retention. Profitable with 65% margins and consistent MRR, nutrIA has strong brand positioning in Chile and a growing user base. Clear expansion paths include LATAM growth and B2B partnerships with nutritionists and health institutions.', 'hand'),
  ('ecom-tools', 'A suite of 80+ e-commerce tools for online sellers.', 'With 80+ Ecom Tools, Sell more stress less!', 'hand'),
  ('everythingweather', 'A US-only weather forecasting app.', 'A US Only Weather app with the most accurate forecasts available.', 'hand'),
  ('virvid-ai', 'Virvid.ai is an AI short-video generator that turns ideas into faceless clips for TikTok, Instagram, and YouTube. It is designed to run largely on autopilot after an initial setup.', 'AI shorts generator that helps creators and businesses turn ideas into viral faceless videos for TikTok, Instagram and YouTube, all on autopilot. Just set it up once and watch your channel grow.', 'hand'),
  ('studyscout', 'StudyScout is a B2C SaaS that aggregates higher-paying online studies and focus groups. Growth has been fully organic with no paid ads, via a repeatable UGC approach, and it includes a 139k-contact email list. The listing describes a lean, high-margin operation with room to scale through content, paid ads, and email. The founder is selling to focus on other projects.', 'StudyScout is a B2C SaaS aggregating high-paying online studies and focus groups. $0 paid ads, growth is 100% organic. Proven viral, repeatable UGC engine with massive upside via scaling content, paid ads, and email marketing. Includes a 139k untapped email list. High-margin, lean operation with strong conversion and significant room to scale revenue quickly.

Selling to pursue other projects.', 'hand')
on conflict (slug) do nothing;
